version: '3.7'
services:
  app:
    build: .
    command: sh -c "ng serve --host 0.0.0.0"
    ports:
      - 4200:4200
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
